config/routes.rb
IfundartsPh::Application.routes.draw do
  root :to => 'ifund#index', :as => 'home'
  match 'about', :to => 'ifund#about', :as => 'about'
  match 'explore(/:category)', :to => 'ifund#explore', :as => 'explore'
  match 'create', :to => 'ifund#create', :as => 'create'
  match 'terms', :to => 'ifund#terms', :as => 'terms'
  match 'login', :to => 'ifund#login', :as => 'login'
  match 'admin', :to => 'ifund#admin', :as => 'admin'
  match 'admin_settings', :to => 'ifund#admin_settings', :as => 'admin_settings', :via => 'post'
  match 'admin_login', :to => 'ifund#admin_login', :as => 'admin_login'
  match 'admin_auth',  :to => 'ifund#admin_auth',  :as => 'admin_auth', :via => :post
  match 'creator', :to => 'ifund#creator', :as => 'creator', :via => :post

  match 'project/:id', :to => 'ifund#project', :as => 'project'
  match 'support/:id', :to => 'ifund#support', :as => 'support', :via => :post
end

app/models/admin_password.rb
class AdminPassword < ActiveRecord::Base
  def authenticates? str
    sha = Digest::SHA1.new << %[#{self.sha1_salt}#{str}]
    sha.to_s == self.sha1_pass
  end
end

app/models/f_b_key.rb
class FBKey < ActiveRecord::Base
  def save_once
    fst = self
    if FBKey.count > 0 then
      fst = FBKey.first
      fst.key = self.key
    else
      fst = self
    end
    fst.save
  end
end

app/models/facebook_key.rb
class FacebookKey < ActiveRecord::Base
  def save_once
    fst = self
    if FacebookKey.count > 0 then
      fst = FacebookKey.first
      fst.key = self.key
    else
      fst = self
    end
    fst.save
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_one :category
  validates :name, :presence => true
  validates :image, :presence => true
  validates :description, :presence => true
  validates :ends_at, :presence => true
  validates :needs, :presence => true

  def fund_pc
    (((self.needs - self.has_got) / self.needs) * 100.0)
  end
end

app/models/project_category.rb
class ProjectCategory < ActiveRecord::Base
  belongs_to :project

  def combien
    Project.where(:category_id => self.id).count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/ifund_controller.rb
class IfundController < ApplicationController
  before_filter :admins_only, :only => [:admin, :admin_settings]
  before_filter :set_fb_key

  def set_fb_key
    @fbkey  = FacebookKey.first
    @fbkey  = (@fbkey ? @fbkey.key : 'FACEBOOK_KEY')
  end

  def index
    @projects = Project.order('ends_at ASC').where(:funded_at => nil).limit 3
    @newbies  = Project.order('created_at ASC').limit 3
    @finished = Project.order('funded_at DESC').where('funded_at IS NOT NULL').limit 3
  end

  def admins_only
    unless session[:admin] then
      redirect_to admin_login_path
    end
  end

  def admin_auth
    if AdminPassword.first.authenticates? request[:adminpass] then
      session[:admin] = true
      redirect_to admin_path
    else
      flash[:login] = %[The password was incorrect.]
      redirect_to admin_login_path
    end
  end

  def admin_settings
    fb  = FacebookKey.first
    fb  = FacebookKey.new unless fb
    fb.key  = request[:fbkey]
    fb.save
    if request[:pass] != request[:pass2] then
      flash[:pass] = %[The two passwords you provided do not match, so the password was not changed.]
    else
      pass  = AdminPassword.first
      pass.delete if pass
      salt  = File.open('/dev/random') {|f| [f.read(10)].pack('m') }
      sha1  = Digest::SHA1.new << %[#{salt}#{request[:pass]}]
      pass  = AdminPassword.create :sha1_pass => sha1.to_s, :sha1_salt => salt
    end
    redirect_to admin_path
  end

  def admin_login
  end

  def admin
  end

  def explore
    @projects   = Project.order('ends_at ASC')
    if request[:category] then
      @projects  = @projects.where(:category_id => request[:category])
    end
    @projects   = @projects.paginate(:page => request[:page])
    @categories = ProjectCategory.order('name ASC')
  end

  def creator
    proj  = Project.new(:name         => request[:name],
                        :image        => ifname,
                        :description  => request[:description],
                        :ends_at      => iends,
                        :needs        => ineeds)

    redirect_to explore_path
  end

  def project
    @project = Project.find_by_id request[:id]
  end

  def support
    @project = Project.find_by_id request[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ifund_helper.rb
module IfundHelper
end

app/views/ifund/about.html.haml
= content_for :title do
  About

%h1 About ¡FundArts!
Many small contributions, one huge impact.<br />
Artists with a project that needs funding will place their projects on this website.<br />
Backers will chip in, and help the project to its completion … and get a little something.<br />

app/views/ifund/admin.html.haml
= content_for :title do
  Administration

Administration

= form_tag admin_settings_path, :method => :post do
  %fieldset
    %legend
      Admin Password
      - if flash[:pass] then
        .error
          = flash[:pass]
    %input{:type => :password, :value => '', :name => :pass}/
  %fieldset
    %legend Admin Password (again)
    %input{:type => :password, :value => '', :name => :pass2}/
  %fieldset
    %legend Facebook Key
    %input{:type => :text, :value => @fbkey, :name => :fbkey}/
  %input{:type => :submit, :value => 'Record'}/

app/views/ifund/admin_login.html.haml
= content_for :title do
  Administration Log-in

Administration Log-in

= form_tag admin_auth_path, :method => :post do
  %fieldset
    %legend
      Administrator Password
      - if flash[:login] then
        .error
          #{flash[:login]}
    %input{:type => :password, :name => :adminpass}/
  %input{:type => :submit, :value => 'Log in'}/

app/views/ifund/create.html.haml
= content_for :title do
  Create a Project

= form_tag creator_path, :method => 'POST', :enctype => 'multipart/form-data' do
  %fieldset
    %legend
      Name Your Project:
      - if flash[:name] then
        .error #{flash[:name]}
    %input{:type => 'text', :name => 'name'}/
  %fieldset
    %legend
      Describe Your Project:
      - if flash[:description] then
        .error #{flash[:description]}
    %textarea{:name => 'description'}
  %fieldset
    %legend
      Give Your Project a Picture:
      - if flash[:pic] then
        .error #{flash[:pic]}
    %input{:type => 'file', :name => 'pic'}/
    %small{:style => 'font-size: small'}
      The files we allow are those that end in <code>.gif</code>, <code>.png</code>, and <code>.pdf</code> <em>only</em>.
  %fieldset
    %legend
      Set a Deadline:
      - if flash[:deadline] then
        .error #{flash[:deadline]}
    %input{:type => 'text', :name => 'deadline'}/
  %fieldset
    %legend
      Set a Target ($):
      - if flash[:target] then
        .error #{flash[:target]}
    %input{:type => 'text', :name => 'target'}/
  %input{:type => 'submit', :value => 'Record'}

app/views/ifund/explore.html.haml
= content_for :title do
  Explore Projects

.projectlist{:class => 'span-8'}
  %ul
    - @categories.each do |category|
      %li
        %a{:href => explore_path(:category => category.id)}
          = category.name
        - comb  = category.combien
        - unless  comb.zero? then
          = surround '(', ')' do
            = comb
- @projects.each do |project|
  .exploreproject{:class => 'span-16 last'}
    .explorepic{:class => 'span-2'}
      %img{:width => '100%', :src => asset_path(project.image)}
    .exploredata{:class => 'span-14 last'}
      .header
        %a{:href => project_path(project.id)}
          = project.name
      .descr
        = project.description
      .counters
        %table{:height => '1em', :style => 'padding: 0px; margin: 0px; background: #dedede; border-radius: 20em 20em 20em 20em; font-size: 2%;'}
          %tr{:height => '1em', :style => 'padding: 0px; margin: 0px;'}
            %td{:height => '1em', :width => %[#{project.fund_pc}%], :style => %[padding: 0px; margin: 0px; border-radius: 20em 20em 20em 20em; background: #121212;  background-image: linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -o-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -moz-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -webkit-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -ms-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0.44, rgb(0,0,0)), color-stop(0.72, rgb(201,201,201)), color-stop(0.86, rgb(61,61,61)));]} &nbsp;
            %td &nbsp;
= will_paginate @projects

app/views/ifund/index.html.haml
= content_for :title do
  Crowd-funding Website for Arts

.projects
  - if @projects.any? then
    .indicator{:class => 'span-24'} Urgent
  - pos = 1
  - @projects.each do |project|
    .project{:class => 'span-8' + ((pos == 3) ? ' last' : '')}
      .header
        %a{:href => project_path(project.id)}
          = project.name
      .pic
        %img{:src => asset_path(project.image)}
      .descr
        = project.description
      .counters
        %table{:height => '1em', :style => 'padding: 0px; margin: 0px; background: #dedede; border-radius: 20em 20em 20em 20em; font-size: 2%;'}
          %tr{:height => '1em', :style => 'padding: 0px; margin: 0px;'}
            %td{:height => '1em', :width => %[#{project.fund_pc}%], :style => %[padding: 0px; margin: 0px; border-radius: 20em 20em 20em 20em; background: #121212; background-image: linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -o-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -moz-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -webkit-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -ms-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0.44, rgb(0,0,0)), color-stop(0.72, rgb(201,201,201)), color-stop(0.86, rgb(61,61,61)));]} &nbsp;
            %td &nbsp;
        .time
          Ends in
          = succeed '.' do
            = time_ago_in_words project.ends_at
      .tools
        = button_to('iFund This!', support_path(project.id))
    - pos = pos + 1
.projects
  - if @newbies.any? then
    .indicator{:class => 'span-24'} Newest
  - pos = 1
  - @newbies.each do |project|
    .project{:class => 'span-8' + ((pos == 3) ? ' last' : '')}
      .header
        %a{:href => project_path(project.id)}
          = project.name
      .pic
        %img{:src => asset_path(project.image)}
      .descr
        = project.description
      .counters
        %table{:height => '1em', :style => 'padding: 0px; margin: 0px; background: #dedede; border-radius: 20em 20em 20em 20em; font-size: 2%;'}
          %tr{:height => '1em', :style => 'padding: 0px; margin: 0px;'}
            %td{:height => '1em', :width => %[#{project.fund_pc}%], :style => %[padding: 0px; margin: 0px; border-radius: 20em 20em 20em 20em; background: #121212; background-image: linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -o-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -moz-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -webkit-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -ms-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0.44, rgb(0,0,0)), color-stop(0.72, rgb(201,201,201)), color-stop(0.86, rgb(61,61,61)));]} &nbsp;
            %td &nbsp;
        .time
          Registered
          = time_ago_in_words project.created_at
          ago
      .tools
        = button_to('iFund This!', support_path(project.id))
    - pos = pos + 1
.projects
  - if @finished.any? then
    .indicator{:class => 'span-24'} Recently Funded
  - pos = 1
  - @finished.each do |project|
    .project{:class => 'span-8' + ((pos == 3) ? ' last' : '')}
      .header
        %a{:href => project_path(project.id)}
          = project.name
      .pic
        %img{:src => asset_path(project.image)}
      .descr
        = project.description
    - pos = pos + 1

app/views/ifund/project.html.haml
= content_for :title do
  = @project.name

.projects
  .project{:class => 'span-8 prepend-8 append-8'}
    .header
      %a{:href => project_path(@project.id)}
        = @project.name
    .pic
      %img{:src => asset_path(@project.image)}
    .descr
      = @project.description
    .counters
      %table{:height => '1em', :style => 'padding: 0px; margin: 0px; background: #dedede; border-radius: 20em 20em 20em 20em; font-size: 2%;'}
        %tr{:height => '1em', :style => 'padding: 0px; margin: 0px;'}
          %td{:height => '1em', :width => %[#{@project.fund_pc}%], :style => %[padding: 0px; margin: 0px; border-radius: 20em 20em 20em 20em; background: #121212; background-image: linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -o-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -moz-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -webkit-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -ms-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0.44, rgb(0,0,0)), color-stop(0.72, rgb(201,201,201)), color-stop(0.86, rgb(61,61,61)));]} &nbsp;
          %td &nbsp;
      .time
        Ends in
        = succeed '.' do
          = time_ago_in_words @project.ends_at
    .tools
      = button_to('iFund This!', support_path(@project.id))

app/views/ifund/support.html.haml
= content_for :title do
  Support
  = @project.name

.projects
  .project{:class => 'span-8 prepend-8 append-8'}
    .header
      %a{:href => project_path(@project.id)}
        = @project.name
    .pic
      %img{:src => asset_path(@project.image)}
    .descr
      = @project.description
    .counters
      %table{:height => '1em', :style => 'padding: 0px; margin: 0px; background: #dedede; border-radius: 20em 20em 20em 20em; font-size: 2%;'}
        %tr{:height => '1em', :style => 'padding: 0px; margin: 0px;'}
          %td{:height => '1em', :width => %[#{@project.fund_pc}%], :style => %[padding: 0px; margin: 0px; border-radius: 20em 20em 20em 20em; background: #121212; background-image: linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -o-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -moz-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -webkit-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -ms-linear-gradient(bottom, rgb(0,0,0) 44%, rgb(201,201,201) 72%, rgb(61,61,61) 86%); background-image: -webkit-gradient(linear, left bottom, left top, color-stop(0.44, rgb(0,0,0)), color-stop(0.72, rgb(201,201,201)), color-stop(0.86, rgb(61,61,61)));]} &nbsp;
          %td &nbsp;
      .time
        Ends in
        = succeed '.' do
          = time_ago_in_words @project.ends_at
    .tools
      %script{:src => 'https://www.paypalobjects.com/js/external/dg.js', :language => 'javascript', :type => 'text/javascript'}
      = form_tag 'https://api-3t.sandbox.paypal.com/nvp', :method => :post do
        %input{:type => :hidden, :name => :SUCCESSURL, :value => project_url(:project => @project.id, :from => :paypal)}/
        %input{:type => :hidden, :name => :RETURNURL, :value => project_url(:project => @project.id, :from => :paypal)}/
        %input{:type => :hidden, :name => :CANCELURL, :value => project_url(:project => @project.id)}/
        %input{:type => :hidden, :name => :SIGNATURE, :value => ''}/
        %input{:type => :hidden, :name => :USER, :value => 'SetExpressCheckout'}/
        %input{:type => :hidden, :name => :PWD, :value => 'SetExpressCheckout'}/
        %input{:type => :hidden, :name => :METHOD, :value => 'SetExpressCheckout'}/
        %input{:type => :hidden, :name => :VERSION, :value => '1.0'}/
        %input{:type => :hidden, :name => :PAYMENT_REQUEST_0_PAYMENTACTION, :value => 'Sale'}/
        %input{:type => :hidden, :name => :PAYMENT_REQUEST_0_CURRENCYCODE, :value => 'USD'}/
        %fieldset
          %legend
            Amount in USD
            = surround '(', ')' do
              %i e.g., 99.95
          %input{:type => :text, :name => :PAYMENT_REQUEST_0_AMT, :value => number_with_delimiter((@project.needs - @project.has_got).round(2))}/
        %input{:type => :image, :alt => 'Pay with Paypal', :src => 'https://www.paypal.com/en_US/i/btn/btn_dg_pay_w_paypal.gif'}/
        - # %img{:id => 'sellingpoint', :src => 'https://www.paypal.com/en_US/i/btn/btn_dg_pay_w_paypal.gif'}/
      %script
        var dg = new PAYPAL.apps.DGFlow({trigger:'sellingpoint', expType: 'instant'});

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      &iexcl;FundArts! &laquo;&bull;&raquo;
      = yield :title
    = stylesheet_link_tag 'application'
    = csrf_meta_tags
  %body
    #main{:class => 'container'}
      #header{:class => 'span-24'}
        #logoface{:class => 'span-8'}
          %a{:href => home_url}
            %img{:src => asset_path('ifundartslogo.png'), :class => 'logoimage', :alt => 'iFundArts!'}
        #tagline{:class => 'span-16 last'}
          Crowd Funding for the Arts
          #explication
            Many small contributions, one huge impact.
            %br/
            Artists with a project that needs funding will place their projects on this website.
            %br/
            Backers will chip in, and help the project to its completion
            &#133;
            and get a little something.
          %ul
            %li
              %a{:href => about_path} About
            %li
              %a{:href => explore_path} Explore
            %li
              %a{:href => create_path} Create a Project
            %li
              %div{:class => 'fb-login-button', :style => 'display: inline;'} Sign In
              %span{:id => 'fbappid', 'appid' => @fbkey.to_s}
              - # %a{:href => login_path, :id => 'signin', :class => 'fb-login-button'} Sign In
            %li{:id => 'gcse'}
              %div{:id  =>  "cse", :style =>  "width: 100%;"} Loading ¡FundArts! Arts Search &#133;
              %script{:src =>  "http://www.google.com/jsapi", :type  =>  "text/javascript"}
              %script{:type  =>  "text/javascript"}
                google.load('search', '1', {style : google.loader.themes.MINIMALIST});
                google.setOnLoadCallback(function() {
                var customSearchOptions = {};  var customSearchControl = new google.search.CustomSearchControl(
                '009300983254775965770:fp_rj7vdc_g', customSearchOptions);
                customSearchControl.setResultSetSize(google.search.Search.FILTERED_CSE_RESULTSET);
                customSearchControl.draw('cse');
                }, true);
      #trunk{:class => 'span-24'}
        #fb-root
        = yield
      #footer{:class => 'span-24'}
        .activity
          %iframe{:src => "//www.facebook.com/plugins/like.php?href=#{CGI.escape(home_url)}&amp;send=false&amp;layout=button_count&amp;width=450&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font=trebuchet+ms&amp;height=21", :scrolling => "no", :frameBorder => "0", :style => "border:none; overflow:hidden; width:450px; height:21px; display:block;", :allowTransparency => "true"}
          %a{:href => about_path} How it Works
          &bull;
          %a{:href => terms_path} Terms and Conditions
          &bull;
          %a{:href => 'http://twitter.com/bayimba'} Twitter
          &bull;
          %a{:href => admin_path} Administration
        .copyright
          &copy; 2011,
          = succeed '.' do
            = link_to 'Bayimba Foundation', 'http://www.bayimba.org/'
          All Rights Reserved
      = javascript_include_tag 'application'